cabal-version: 2.4
name: bench-haskell
version: 0.1.0.0
build-type: Simple

executable benchHaskellCodec
  main-is: Main.hs
  hs-source-dirs: app, generated
  other-modules: Proto.Perf, Proto.Perf_Fields
  build-depends:
      base >=4.13 && <4.14,
      bytestring,
      deepseq,
      lens-family ==2.1.3,
      proto-lens ==0.7.1.7,
      proto-lens-runtime ==0.7.0.8,
      text,
      vector ==0.13.2.0
  default-language: Haskell2010
  ghc-options: -O2 -threaded -rtsopts -fno-full-laziness
